<?php
/**
 * One-time DB config wizard for cPanel. DELETE after setup complete.
 * Open: https://calculator.suriainfiniti.com/setup-config-web.php
 */
require_once __DIR__ . '/includes/bootstrap.php';

$configPath = __DIR__ . '/config.php';
$message = '';
$error = '';
$defaults = [
    'db_host' => 'localhost',
    'db_name' => 'suriainfico_suriacalculator',
    'db_user' => 'suriainfico_usercalculator',
    'db_pass' => '',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';

    if (!$dbName || !$dbUser) {
        $error = 'Database name and user are required.';
    } else {
        try {
            $dsn = sprintf('mysql:host=%s;dbname=%s;charset=utf8mb4', $dbHost, $dbName);
            new PDO($dsn, $dbUser, $dbPass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            $csrfSecret = bin2hex(random_bytes(32));
            $config = <<<'PHP'
<?php
/**
 * Suria Solar Calculator — live configuration (generated by setup-config-web.php)
 * DELETE setup-config-web.php after confirming admin login works.
 */

return [
    'db' => [
        'host' => '%s',
        'name' => '%s',
        'user' => '%s',
        'pass' => '%s',
        'charset' => 'utf8mb4',
    ],

    'app' => [
        'env' => 'production',
        'allowed_origins' => [
            'https://calculator.suriainfiniti.com',
            'https://suriainfiniti.com',
            'https://suria-solar-calculator.vercel.app',
        ],
        'privacy_policy_version' => '1.0',
    ],

    'csrf' => [
        'secret' => '%s',
        'ttl_seconds' => 3600,
    ],

    'turnstile' => [
        'secret_key' => '1x0000000000000000000000000000000AA',
    ],

    'mail' => [
        'enabled' => true,
        'to' => 'info@suriainfiniti.com',
        'from' => 'noreply@suriainfiniti.com',
        'from_name' => 'Suria Solar Calculator',
        'smtp_host' => 'localhost',
        'smtp_port' => 587,
        'smtp_user' => '',
        'smtp_pass' => '',
        'smtp_secure' => 'tls',
    ],

    'rate_limit' => [
        'max_requests' => 5,
        'window_seconds' => 3600,
    ],

    'google' => [
        'places_api_key' => '',
    ],
];
PHP;

            $escapedPass = addcslashes($dbPass, "\\'");
            $contents = sprintf(
                $config,
                addcslashes($dbHost, "\\'"),
                addcslashes($dbName, "\\'"),
                addcslashes($dbUser, "\\'"),
                $escapedPass,
                $csrfSecret
            );

            if (file_put_contents($configPath, $contents) === false) {
                throw new RuntimeException('Could not write config.php — check folder permissions in File Manager.');
            }

            $message = 'config.php saved and database connection OK. Next: import schema.sql in phpMyAdmin, then open setup-web.php to create admin login.';
        } catch (Throwable $e) {
            $msg = $e->getMessage();
            if (stripos($msg, 'Access denied') !== false) {
                $error = 'MySQL access denied — check database user, password, and that user is added to the database in cPanel.';
            } elseif (stripos($msg, 'Unknown database') !== false) {
                $error = 'Database not found — create it in cPanel → MySQL Databases, then import schema.sql.';
            } else {
                $error = $msg;
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Suria Calculator — DB Setup</title>
  <style>
    body { font-family: system-ui, sans-serif; background: #FAF8F5; color: #0C2637; max-width: 480px; margin: 40px auto; padding: 24px; }
    .card { background: #fff; border: 1px solid #ECECEC; border-radius: 12px; padding: 24px; }
    h1 { font-size: 20px; margin-bottom: 8px; }
    p, li { font-size: 14px; color: #666; line-height: 1.6; }
    label { display: block; font-weight: 600; font-size: 13px; margin: 12px 0 4px; }
    input { width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 8px; }
    button { width: 100%; margin-top: 16px; padding: 12px; background: #F47421; color: #fff; border: none; border-radius: 8px; font-weight: 700; cursor: pointer; }
    .ok { background: #e8f5e9; color: #2e7d32; padding: 12px; border-radius: 8px; margin-bottom: 12px; font-size: 14px; }
    .err { background: #fdecea; color: #c62828; padding: 12px; border-radius: 8px; margin-bottom: 12px; font-size: 14px; }
    code { background: #f5f5f5; padding: 2px 6px; border-radius: 4px; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Database Setup</h1>
    <p>Admin login needs <code>config.php</code> with your cPanel MySQL details.</p>
    <?php if ($message): ?><div class="ok"><?= htmlspecialchars($message) ?></div><?php endif; ?>
    <?php if ($error): ?><div class="err"><?= htmlspecialchars($error) ?></div><?php endif; ?>
    <form method="post">
      <label>DB Host</label>
      <input name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? $defaults['db_host']) ?>">
      <label>DB Name (cPanel format)</label>
      <input name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? $defaults['db_name']) ?>" required>
      <label>DB User (cPanel format)</label>
      <input name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? $defaults['db_user']) ?>" required>
      <label>DB Password</label>
      <input type="password" name="db_pass" required>
      <button type="submit">Save config.php &amp; Test Connection</button>
    </form>
    <p style="margin-top:16px">After save: phpMyAdmin → Import <code>schema.sql</code> → open <code>setup-web.php</code></p>
  </div>
</body>
</html>
